name: On Push

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
#      - name: Install dependencies
#        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          config-file: e2e-tests/cypress.json
#
#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v1
#      with:
#        submodules: recursive
#    - name: Setup Node
#      uses: actions/setup-node@v1
#      with:
#        node-version: 10.x
#    - name: Install dependencies
#      run: yarn
#    - name: Lint services
#      run: yarn lint
#      env:
#        CI: true
#
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          submodules: recursive
#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 10.x
#      - name: Install dependencies
#        run: yarn
#      - name: Build
#        run: yarn build
#      - name: Unit tests
#        run: yarn test
#      - name: Deploy services
#        run: yarn deploy:test
#        env:
#          CI: true
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: Integration tests
#        run: yarn test:integration
#        env:
#          CI: true
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: Clean up
#        run: yarn destroy:test
#        env:
#          CI: true
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
